## **TSEP**- **Test**
##**Name** - **Md Tahseen Raza**
##**System** **id** - **2021470193**

##Question 1 of word file

In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

num_elements = arr.size

itemsize = arr.itemsize

total_bytes = num_elements * itemsize

print("Number of elements in the array: ", num_elements)
print("Length of one array element in bytes: ", itemsize)
print("Total bytes consumed by the elements: ", total_bytes)

Number of elements in the array:  5
Length of one array element in bytes:  8
Total bytes consumed by the elements:  40


##Question 2 of word file

## **Concatenation**

In [6]:
arr2 = np.array([6, 7, 8])

concat_arr = np.concatenate((arr, arr2))

print("Concatenated array: \n", concat_arr)

Concatenated array: 
 [1 2 3 4 5 6 7 8]


## **Any**

In [4]:
any_greater = np.any(arr > 3)

print("Are any elements greater than 3? ", any_greater)

Are any elements greater than 3?  True


## **Shape**

In [5]:
arr_shape = arr.shape

print("Shape of the array: ", arr_shape)

Shape of the array:  (5,)


## **Reshape**

In [11]:
reshaped_arr = arr.reshape(1, 5)
print("Reshaped array: \n", reshaped_arr)

Reshaped array: 
 [[1 2 3 4 5]]


## **Append**

In [12]:
appended_arr = np.append(arr, 6)

print("Appended array: \n", appended_arr)

Appended array: 
 [1 2 3 4 5 6]


### **Extend**

In [ ]:
extended_arr = np.concatenate((arr, arr2))

print("Extended array: \n", extended_arr)