##**TSEP Test**

##Submitted By = **Md. Tahseen Raza**
##System Id = **2021470193**

#### 30. How to find common values between two arrays? (★☆☆)

In [3]:
array1 = [1, 2, 3, 4, 5]
array2 = [4, 5, 6, 7, 8]

common_values = set(array1) & set(array2)
print(common_values)


{4, 5}


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [4]:
import numpy as np

np.seterr(all='ignore')


{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [6]:
from datetime import datetime, timedelta

today = datetime.now().date()

yesterday = today - timedelta(days=1)

tomorrow = today + timedelta(days=1)

print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)


Yesterday: 2024-04-15
Today: 2024-04-16
Tomorrow: 2024-04-17


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [7]:
from datetime import datetime, timedelta

start_date = datetime(2016, 7, 1)
end_date = datetime(2016, 7, 31)

dates_in_july_2016 = [start_date + timedelta(days=i) for i in range((end_date - start_date).days + 1)]

for date in dates_in_july_2016:
    print(date.date())


2016-07-01
2016-07-02
2016-07-03
2016-07-04
2016-07-05
2016-07-06
2016-07-07
2016-07-08
2016-07-09
2016-07-10
2016-07-11
2016-07-12
2016-07-13
2016-07-14
2016-07-15
2016-07-16
2016-07-17
2016-07-18
2016-07-19
2016-07-20
2016-07-21
2016-07-22
2016-07-23
2016-07-24
2016-07-25
2016-07-26
2016-07-27
2016-07-28
2016-07-29
2016-07-30
2016-07-31


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [9]:
import numpy as np

A = np.array([1, 2, 3], dtype=float)
B = np.array([4, 5, 6], dtype=float)


np.multiply(A, -0.5, out=A)
np.add(A, B, out=A)

print(A)


[3.5 4.  4.5]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [10]:
import numpy as np

random_array = np.random.rand(5) * 10
integer_part_1 = random_array.astype(int)

integer_part_2 = np.floor(random_array)

integer_part_3 = np.array(list(map(int, random_array)))

integer_part_4 = np.array([int(x) for x in random_array])

print("Method 1:", integer_part_1)
print("Method 2:", integer_part_2)
print("Method 3:", integer_part_3)
print("Method 4:", integer_part_4)


Method 1: [1 8 0 1 0]
Method 2: [1. 8. 0. 1. 0.]
Method 3: [1 8 0 1 0]
Method 4: [1 8 0 1 0]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [11]:
import numpy as np

matrix = np.arange(5).reshape(1, -1) + np.arange(5).reshape(-1, 1)

print(matrix)


[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [ ]:
import numpy as np

def generate_integers(n):
    for i in range(n):
        yield i

generator = generate_integers(10)

array_from_generator = np.fromiter(generator, dtype=int)

print(array_from_generator)


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [14]:
import numpy as np

vector = np.linspace(0, 1, 12)[1-1]

print(vector)


0.0


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [15]:
import numpy as np

random_vector = np.random.rand(10)

sorted_vector = np.sort(random_vector)

print("Original random vector:", random_vector)
print("Sorted vector:", sorted_vector)


Original random vector: [0.77003025 0.4468405  0.99256366 0.76678446 0.22379369 0.61287385
 0.36427522 0.53643372 0.66410592 0.74743133]
Sorted vector: [0.22379369 0.36427522 0.4468405  0.53643372 0.61287385 0.66410592
 0.74743133 0.76678446 0.77003025 0.99256366]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [16]:
import numpy as np

small_array = np.array([1, 2, 3, 4, 5])

result = sum(small_array)

print("Sum using built-in sum() function:", result)



Sum using built-in sum() function: 15


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [17]:
import numpy as np

A = np.random.rand(5)
B = np.random.rand(5)

are_equal = np.array_equal(A, B)

print("Arrays A and B are equal:", are_equal)


Arrays A and B are equal: False


#### 43. Make an array immutable (read-only) (★★☆)

In [18]:
import numpy as np

my_array = np.array([1, 2, 3, 4, 5])

my_array.setflags(write=False)

try:
    my_array[0] = 10
except ValueError as e:
    print("Error occurred:", e)

print("Is the array immutable?", not my_array.flags.writeable)


Error occurred: assignment destination is read-only
Is the array immutable? True


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [19]:
import numpy as np

cartesian_coordinates = np.random.rand(10, 2)

x = cartesian_coordinates[:, 0]
y = cartesian_coordinates[:, 1]

r = np.hypot(x, y)
theta = np.arctan2(y, x)

polar_coordinates = np.column_stack((r, theta))

print("Cartesian coordinates:")
print(cartesian_coordinates)
print("\nPolar coordinates:")
print(polar_coordinates)


Cartesian coordinates:
[[0.90390737 0.21746632]
 [0.19141164 0.23292193]
 [0.09158013 0.02952498]
 [0.28612959 0.49123521]
 [0.11055691 0.13829401]
 [0.74310504 0.72179924]
 [0.63433816 0.24947992]
 [0.08929876 0.80718081]
 [0.40292287 0.00600392]
 [0.56252762 0.61328156]]

Polar coordinates:
[[0.92969895 0.2360978 ]
 [0.30148141 0.88291255]
 [0.09622185 0.311874  ]
 [0.56849113 1.04336654]
 [0.17705385 0.89640069]
 [1.0359533  0.77085503]
 [0.68163416 0.37470999]
 [0.81210537 1.46061395]
 [0.4029676  0.01489983]
 [0.83219685 0.8285365 ]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [20]:
import numpy as np

random_vector = np.random.rand(10)

print("Original random vector:", random_vector)

max_index = np.argmax(random_vector)

random_vector[max_index] = 0

print("Vector with maximum value replaced by 0:", random_vector)


Original random vector: [0.50359979 0.22753572 0.86999452 0.1584686  0.48443549 0.41326546
 0.96390138 0.8132249  0.35422293 0.6621296 ]
Vector with maximum value replaced by 0: [0.50359979 0.22753572 0.86999452 0.1584686  0.48443549 0.41326546
 0.         0.8132249  0.35422293 0.6621296 ]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [22]:
import numpy as np

grid_size = 5


x = np.linspace(0, 1, grid_size)
y = np.linspace(0, 1, grid_size)

X, Y = np.meshgrid(x, y)

structured_array = np.zeros((grid_size * grid_size,), dtype=[('x', float), ('y', float)])
structured_array['x'] = X.flatten()
structured_array['y'] = Y.flatten()

print(structured_array)


[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )
 (0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)
 (0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )
 (0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)
 (0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [23]:
import numpy as np

X = np.array([1, 2, 3])
Y = np.array([4, 5, 6])

C = 1 / (X.reshape(-1, 1) - Y)

print("Cauchy matrix C:")
print(C)


Cauchy matrix C:
[[-0.33333333 -0.25       -0.2       ]
 [-0.5        -0.33333333 -0.25      ]
 [-1.         -0.5        -0.33333333]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [ ]:
import numpy as np

print("Integer scalar types:")
for dtype in [np.int8, np.int16, np.int32, np.int64]:
    info = np.iinfo(dtype)
    print(f"{dtype.__name__}: Min={info.min}, Max={info.max}")

print("\nUnsigned integer scalar types:")
for dtype in [np.uint8, np.uint16, np.uint32, np.uint64]:
    info = np.iinfo(dtype)
    print(f"{dtype.__name__}: Min={info.min}, Max={info.max}")

print("\nFloating-point scalar types:")
for dtype in [np.float32, np.float64]:
    info = np.finfo(dtype)
    print(f"{dtype.__name__}: Min={info.min}, Max={info.max}")



#### 49. How to print all the values of an array? (★★☆)

In [24]:
my_array = [1, 2, 3, 4, 5]
for value in my_array:
    print(value)


1
2
3
4
5


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [25]:
def find_closest_value(vector, target):
    closest_value = None
    min_difference = float('inf')
    for value in vector:
        difference = abs(value - target)
        if difference < min_difference:
            min_difference = difference
            closest_value = value

    return closest_value

vector = [1, 3, 5, 7, 9]
target = 6
closest = find_closest_value(vector, target)
print("Closest value to", target, "in the vector:", closest)


Closest value to 6 in the vector: 5
